# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123Nc3fabQ3_LL_KjTAOM-Xs_0ErpgCgJ

CATEGORY FORECASTING
"""

import pandas as pd
from prophet import Prophet
import warnings

warnings.filterwarnings("ignore")

# =====================================================
# LOAD DATA
# =====================================================

df = pd.read_csv(
    "DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

# =====================================================
# DATE CONVERSION
# =====================================================

df['order date (DateOrders)'] = pd.to_datetime(
    df['order date (DateOrders)']
)

# =====================================================
# CATEGORY PRICE LOOKUP
# =====================================================

category_price = (
    df.groupby('Category Name')
      .agg({
          'Sales': 'sum',
          'Order Item Quantity': 'sum'
      })
      .reset_index()
)

category_price['Avg_Selling_Price'] = (
    category_price['Sales']
    /
    category_price['Order Item Quantity']
)

price_lookup = dict(
    zip(
        category_price['Category Name'],
        category_price['Avg_Selling_Price']
    )
)

# =====================================================
# MONTHLY CATEGORY DEMAND
# =====================================================

monthly_qty = (
    df.groupby([
        'Category Name',
        pd.Grouper(
            key='order date (DateOrders)',
            freq='ME'
        )
    ])['Order Item Quantity']
    .sum()
    .reset_index()
)

monthly_qty.columns = [
    'Category Name',
    'Date',
    'Quantity'
]

# =====================================================
# GLOBAL FORECAST MONTH LABELS
# =====================================================

global_last_month = (
    monthly_qty['Date']
    .max()
)

forecast_labels = pd.date_range(
    start=global_last_month + pd.offsets.MonthEnd(1),
    periods=6,
    freq='ME'
).strftime('%Y-%m')

# =====================================================
# FORECASTING
# =====================================================

forecast_results = []

categories = (
    monthly_qty['Category Name']
    .unique()
)

for category in categories:

    try:

        category_data = (
            monthly_qty[
                monthly_qty['Category Name']
                == category
            ]
            .copy()
        )

        # Fill missing months

        category_data = (
            category_data
            .set_index('Date')
            .asfreq('ME')
        )

        category_data['Quantity'] = (
            category_data['Quantity']
            .fillna(0)
        )

        category_data = (
            category_data
            .reset_index()
        )

        # Need at least 6 periods

        if len(category_data) < 6:
            continue

        prophet_df = pd.DataFrame({

            'ds':
                category_data['Date'],

            'y':
                category_data['Quantity']

        })

        model = Prophet(
            yearly_seasonality=True,
            weekly_seasonality=False,
            daily_seasonality=False
        )

        model.fit(prophet_df)

        future = model.make_future_dataframe(
            periods=6,
            freq='ME'
        )

        forecast = model.predict(
            future
        )

        future_forecast = (
            forecast
            .tail(6)
            .copy()
        )

        avg_price = (
            price_lookup.get(
                category,
                0
            )
        )

        for i, (_, row) in enumerate(
            future_forecast.iterrows()
        ):

            forecast_qty = max(
                0,
                round(row['yhat'])
            )

            lower_bound = max(
                0,
                round(row['yhat_lower'])
            )

            upper_bound = max(
                forecast_qty,
                round(row['yhat_upper'])
            )

            forecast_revenue = round(
                forecast_qty
                *
                avg_price,
                2
            )

            forecast_results.append({

                'Category Name':
                    category,

                'Forecast Month':
                    forecast_labels[i],

                'Forecast Qty':
                    forecast_qty,

                'Forecast Revenue':
                    forecast_revenue,

                'Lower Bound':
                    lower_bound,

                'Upper Bound':
                    upper_bound

            })

    except Exception as e:

        print(
            f"Failed -> {category}: {e}"
        )

# =====================================================
# OUTPUT
# =====================================================

forecast_df = pd.DataFrame(
    forecast_results
)

print(
    "Rows Generated:",
    len(forecast_df)
)

if not forecast_df.empty:

    forecast_df = (
        forecast_df
        .sort_values(
            [
                'Category Name',
                'Forecast Month'
            ]
        )
    )

    forecast_df.to_excel(
        "Forecast_Category.xlsx",
        index=False
    )

    print(
        "Forecast_Category.xlsx created successfully"
    )

    print(
        forecast_df.head()
    )

else:

    print(
        "No forecast rows generated"
    )

"""PRODUCT FORECASTING"""

import pandas as pd
from prophet import Prophet
import warnings

warnings.filterwarnings("ignore")

# =====================================================
# LOAD DATA
# =====================================================

df = pd.read_csv(
    "DataCoSupplyChainDataset.csv",
    encoding="latin1"
)

# =====================================================
# DATE CONVERSION
# =====================================================

df['order date (DateOrders)'] = pd.to_datetime(
    df['order date (DateOrders)']
)

# =====================================================
# PRODUCT PRICE LOOKUP
# =====================================================

product_price = (
    df.groupby(
        ['Product Card Id', 'Product Name']
    )
    .agg({
        'Sales': 'sum',
        'Order Item Quantity': 'sum'
    })
    .reset_index()
)

product_price['Avg_Selling_Price'] = (
    product_price['Sales']
    /
    product_price['Order Item Quantity']
)

price_lookup = dict(
    zip(
        product_price['Product Card Id'],
        product_price['Avg_Selling_Price']
    )
)

# =====================================================
# MONTHLY PRODUCT DEMAND
# =====================================================

monthly_qty = (
    df.groupby([
        'Product Card Id',
        'Product Name',
        pd.Grouper(
            key='order date (DateOrders)',
            freq='ME'
        )
    ])['Order Item Quantity']
    .sum()
    .reset_index()
)

monthly_qty.columns = [
    'Product Card Id',
    'Product Name',
    'Date',
    'Quantity'
]

# =====================================================
# GLOBAL FORECAST MONTH LABELS
# =====================================================

global_last_month = (
    monthly_qty['Date']
    .max()
)

forecast_labels = pd.date_range(
    start=global_last_month + pd.offsets.MonthEnd(1),
    periods=6,
    freq='ME'
).strftime('%Y-%m')

# =====================================================
# FORECASTING
# =====================================================

forecast_results = []

products = (
    monthly_qty[
        ['Product Card Id', 'Product Name']
    ]
    .drop_duplicates()
)

for _, product_row in products.iterrows():

    try:

        product_id = product_row['Product Card Id']
        product_name = product_row['Product Name']

        product_data = (
            monthly_qty[
                monthly_qty['Product Card Id']
                == product_id
            ]
            .copy()
        )

        # ----------------------------------
        # Fill Missing Months
        # ----------------------------------

        product_data = (
            product_data
            .set_index('Date')
            .asfreq('ME')
        )

        product_data['Quantity'] = (
            product_data['Quantity']
            .fillna(0)
        )

        product_data = (
            product_data
            .reset_index()
        )

        if len(product_data) < 6:
            continue

        prophet_df = pd.DataFrame({

            'ds':
                product_data['Date'],

            'y':
                product_data['Quantity']

        })

        model = Prophet(
            yearly_seasonality=True,
            weekly_seasonality=False,
            daily_seasonality=False
        )

        model.fit(prophet_df)

        future = model.make_future_dataframe(
            periods=6,
            freq='ME'
        )

        forecast = model.predict(
            future
        )

        future_forecast = (
            forecast
            .tail(6)
            .copy()
        )

        avg_price = (
            price_lookup.get(
                product_id,
                0
            )
        )

        for i, (_, row) in enumerate(
            future_forecast.iterrows()
        ):

            forecast_qty = max(
                0,
                round(row['yhat'])
            )

            lower_bound = max(
                0,
                round(row['yhat_lower'])
            )

            upper_bound = max(
                forecast_qty,
                round(row['yhat_upper'])
            )

            forecast_revenue = round(
                forecast_qty
                *
                avg_price,
                2
            )

            forecast_results.append({

                'Product Card Id':
                    product_id,

                'Product Name':
                    product_name,

                'Forecast Month':
                    forecast_labels[i],

                'Forecast Qty':
                    forecast_qty,

                'Forecast Revenue':
                    forecast_revenue,

                'Lower Bound':
                    lower_bound,

                'Upper Bound':
                    upper_bound

            })

    except Exception as e:

        print(
            f"Failed -> {product_name}: {e}"
        )

# =====================================================
# FINAL OUTPUT
# =====================================================

forecast_df = pd.DataFrame(
    forecast_results
)

print(
    "Rows Generated:",
    len(forecast_df)
)

if not forecast_df.empty:

    forecast_df = (
        forecast_df
        .sort_values(
            [
                'Product Name',
                'Forecast Month'
            ]
        )
    )

    forecast_df.to_excel(
        "Forecast_Product.xlsx",
        index=False
    )

    print(
        "Forecast_Product.xlsx created successfully"
    )

    print(
        forecast_df.head()
    )

else:

    print(
        "No forecast rows generated"
    )